/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * MOT status codes
 */
export type MotStatusCodes = "VALID" | "NOT_VALID" | "NO_DETAILS" | "AGE_EXEMPTION";

export interface MotHistory {
  /**
   * Vehicle registration number
   */
  registration: string;
  /**
   * Vehicle make
   */
  make?: string;
  /**
   * Vehicle model
   */
  model?: string;
  /**
   * MOT test expiry date
   */
  expiryDate?: string | null;
  status: MotStatusCodes;
}
