/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MotHistory {
  /**
   * Vehicle registration number
   */
  registration: string;
  /**
   * Vehicle make
   */
  make?: string;
  /**
   * Vehicle model
   */
  model?: string;
  /**
   * MOT test expiry date
   */
  expiryDate?: string | null;
  status: MotStatusCodes;
}

/**
 * MOT status codes
 */
export const enum MotStatusCodes {
  VALID = "Valid",
  NOT_VALID = "Not valid",
  NO_DETAILS = "No details",
  AGE_EXEMPTION = "Age exemption"
}
